'use strict';

var app = angular
  .module('foxwayApp', [
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngRoute',
    'pascalprecht.translate',
  ])
  .config(function ($routeProvider, $translateProvider) {

      // Translations
    $translateProvider.translations('en', {
    	"addDateInName": "Add Date In Name",
    	"addDateInNameDescr": "(YYYYMMDDhhmmss)",
        "addDestination": "Add destination",        
        "advancedSettings": "Advanced settings",
        "editDestination": "Edit destination",
    	"addFileDestinations": "Add File Destinations",
    	"NEW_AUTO_GENERATE": "Add Number",
    	"GEN_DATE_TIME_ID": "Add Number In Name",
    	"addNumberInNameDescr": "(000,001,002...)",
    	"APPEND": "Add to PDF Folder",
    	"allEdges": "All edges",
    	"allFilePathDetails": "All File Path Details",
    	"allFilePathsAvailable": "All File Paths Available",
    	"allFilePathInfo": "All File Path Info...",
    	"allTemplates": "All templates",
    	"appTitle": "Workflow Scan",
        "archivalSmallFileSize": "Archival - Small File Size",
        "archivalSmallFileSizeDesc": "This option is best for standard business documents that is stored electronically for record keeping purpose<br/><br/>Using this setting will result in the smallest file sizes and normal image quality.",
        "auditCopyDestinations": "Audit copy destination",
    	"AUTO": "Auto",
    	"autoContrast": "Auto Contrast",
    	"autoDetect": "Auto Detect",
    	"autoDetectDescr": "System identifies the size of the originals",
    	"Suppression_AUTO": "Auto Suppression",
        "Suppression_OFF": "Off",
    	"backgroundSuppression": "Background Suppression",
    	"BLACK_AND_WHITE": "Black and white",
    	"blankPaperManagement": "Blank Paper Management",
		"bottom": "Bottom",
    	"brightness": "Brightness",
        "imageOptions_0": 'Normal',
        "imageOptions_33": '+1',
        "imageOptions_66": '+2',
        "imageOptions_99": '+3',
        "imageOptions_-33": '-1',
        "imageOptions_-66": '-2',
        "imageOptions_-99": '-3',
        "imageOptions_50": '+1',
        "imageOptions_100": '+2',
        "imageOptions_-50": '-1',
        "imageOptions_-100": '-2',
    	"buildJob": "Build Job",
    	"cancel": "Cancel",
		"close": "Close",
    	"colour": "Colour",
    	"contrast": "Contrast",
		"custom": "Custom",
    	"customScanArea": "Custom Scan Area",
    	"customScanAreaDescr": "Manually enter the size of the original",
		"darken": "Darken",
    	"default": "DEFAULT",
    	"detailsFor": "Details for",
    	"doc": "DOC",
    	"documentManagement": "Document Management",
        "documentPath": "Document Path",
    	"dontHideBlankPages": "Don't Hide Blank Pages",
    	"NEW_EXACT": "Don't Save",
    	"doubleSided": "Double-sided",
    	"edgeErase": "Edge Erase",
		"existingFile": "existing file",
    	"fileFormat": "File Format",
    	"fileName": "File Name",
    	"filingOptions": "Filing options",
        "filingProtocol": "Filing Protocol",
    	"format": "Format",
        "foxwayApp": "Foxway App",
    	"JFIF_JPEG": "JPEG",
    	"PDF": "PDF",
    	"PDF/A-1b": "PDF/A",
    	"XSM_TIFF_V6": "TIFF",
    	"XPS": "XPS",
    	"foxwayScan": "Foxway Scan",
    	"FULL_COLOR": "Full color",
    	"GRAYSCALE": "Greyscale",
		"guest": "Guest",
        "quality_0": "Normal",
        "filesize_0": "Small",
        "quality_128": "Higher",
        "filesize_128": "Larger",
        "quality_256": "Highest",
        "filesize_256": "Largest",
    	"OMIT_ALL_BLANK_PAGES": "Hide Blank Pages",
    	"higherQuality": "Higher Quality",
    	"higherQualityDescr": "produces larger files with better image quality.",
    	"highestQuality": "Highest Quality",
    	"highestQualityDescr": "produces the largest files with maximum image quality.",
    	"highQualityPrinting": "High Quality Printing",
        "highQualityPrintingDesc": "This setting is best for business documents containing detailed graphics and photos<br/><br/>Using this setting will result in large file sizes and the highest image quality.",
    	"ifFileAlreadyExists": "If File Already Exists",
    	"IMAGE_ONLY": "Image Only",
    	"imageOptions": "Image Options",
    	"imageEnhancement": "Image Enhancement",
    	"INCLUDE_ALL_PAGES": "Include Blank Pages",
    	"individualEdges": "Individual Edges",
    	"jobAssembly": "Job Assembly",
    	"LANDSCAPE": "Landscape",
		"largeFileWarning": "Large files not ideal for transmitting over the network.",
    	"lastUpdated": "Last updated",
    	"largestFileSize": "Largest File Size",
    	"layoutAdjustment": "Layout Adjustment",
		"left": "Left",
		"length": "Length",
		"less": "Less",
    	"lighten": "Lighten",
    	"lying": "Lying",
    	"machineTemplates": "Machine templates",
    	"MAP": "Map",
		"more": "More",
    	"multiPage": "Multi Page",
        "originalSize_AUTO": 'Auto detect',
        "originalSize_MIXED": 'Mixed Size Originals',
        "originalSize_MANUAL": 'Custom',
        "originalSize_NA_5.5x7LEF": "5.5x7 Portrait",
        "originalSize_NA_5.5x7SEF": "5.5x7 Landscape",
        "originalSize_NA_5.5x8.5LEF": "5.5x8.5 Portrait",
        "originalSize_NA_5.5x8.5SEF": "5.5x8.5 Landscape",
        "originalSize_NA_8.5x11LEF": "8.5x11 Portrait",
        "originalSize_NA_8.5x11SEF": "8.5x11 Landscape",
        "originalSize_NA_8.5x13SEF": "8.5x13 Landscape",
        "originalSize_NA_8.5x14SEF": "8.5x14 Landscape",
        "originalSize_NA_11x17SEF": "11x17 Landscape",
        "originalSize_ISO_A5LEF": "A5 Portrait",
        "originalSize_ISO_A5SEF": "A5 Landscape",
        "originalSize_ISO_A4LEF": "A4 Portrait",
        "originalSize_ISO_A4SEF": "A4 Landscape",
        "originalSize_ISO_A3SEF": "A3 Landscape",
        "originalSize_ISO_A3LEF": "A3 Portrait",
        "originalSize_JIS_B4SEF": "JIS B4 Landscape",
        "originalSize_JIS_B5LEF": "JIS B5 Portrait",
        "originalSize_JIS_B5SE": "JIS B5 Landscape",
    	"mixedSizeOriginals": "Mixed Size Originals",
    	"mixedSizeOriginalsDescr": "Scan originals of different sizes at one time from the Document Feeder.",
    	"NEWSPAPER_AND_MAGAZINE": "Newspaper / Magazie",
    	"newSettingsMayNotBeOptimised": "New settings may not be optimised for the selected scan preset.",
		"normal": "Normal",
		"normalQuality": "Normal Quality",
		"normalQualityDescr": "produces smaller files with good image quality.",
        "ocr": "OCR",
        "ocrDesc": "This setting is best for documents that will be processed by optical character recognition software.<br/><br/>Using this setting will result in large file sizes and the highest image quality.",
    	"off": "Off",
    	"ok": "OK",
    	"on": "On",
    	"oneFilePerPage": "One File Per Page",
    	"options": "Options",
        "originalOrientation": "Original Orientation",
        "originalOrientationDesc": "<b>Portrait</b> and <b>Landscape Originals</b> refer to the images on the original documents. With these selections you can load originals either upright or sideways and the device will rotate it appropriatly.<br/><br/><b>Upright images</b> and <b>Sideway Images</b> refer to the direction the images are loaded in the Document Feeder.<br/><br/>If you are using Document Glass, the orientation is as seen before turning it over.",
    	"originalSize": "Original Size",
    	"originalSizeAutoDetectDescr1": "Specify how the system determines the size of the originals:",
    	"originalType": "Original Type",
    	"OVERWRITE": "Overwrite",
    	"manualContrast_TRUE": "Auto contrast",
        "manualContrast_FALSE": "Manual contrast",
    	"multipleFormats": "Multiple Formats",
    	"PHOTO": "Photo",
    	"MIXED": "Photo and Text",
        "PORTRAIT": "Portrait",
    	"portraitOriginals": "Portrait Originals",
    	"presetScanArea": "Preset Scan Area",
    	"presetScanAreaDescr": "Define the scan area using standard paper size dimensions. Useful for scanning receipts.",
    	"ONE_SIDED": "1-Sided",
    	"outputColour": "Output Colour",
    	"pastel": "Pastel",
    	"presets": "Presets",
    	"presetScanAreaHelpText": "You are specifying the area that will be scanned.",
    	"qualityFileSize": "Quality / File Size",
        "ready": "Ready",
    	"readyToScan": "Ready to scan your job",
    	"remoteSessionIsActive": "Remote Session is active",
    	"remoteTemplates": "Remote templates",
		"remoteUser": "Remote User",
        "repositoryAlias": "Repository Alias",
        "repositoryName": "Repository Name",
    	"resolution": "Resolution",
    	"RES_72X72": "72 dpi",
    	"RES_100X100": "100 dpi",
    	"RES_150X150": "150 dpi",
    	"RES_200X200": "200 dpi",
    	"RES_300X300": "300 dpi",
    	"RES_400X400": "400 dpi",
    	"RES_600X600": "600 dpi",
        "RES_72X72_DESC": "<h2>72 dpi:</h2>Acceptable image quality for onscreen viewing.<br/><br/>Smallest file size.<br/><br/>Suitable for onscreen viewing only. Not good for print quality.",
        "RES_100X100_DESC": "<h2>100 dpi:</h2>Good image quality for onscreen viewing.<br/><br/>Small file size.<br/><br/>Best suited for onscreen viewing. Not best for print quality.",
        "RES_150X150_DESC": "<h2>150 dpi:</h2>Good image quality for onscreen viewing.<br/><br/>Small file size.<br/><br/>Best suited for onscreen viewing. Not best for print quality.",
        "RES_200X200_DESC": "<h2>200 dpi:</h2>Good image quality.<br/><br/>Moderate file size.<br/><br/>Best for standard office documents and photographs.",
        "RES_300X300_DESC": "<h2>300 dpi:</h2>High image quality.<br/><br/>Produces large file size.<br/><br/>Offers better quality for standard office documents and photographs. Recommended for automated processing and OCR.",
        "RES_400X400_DESC": "<h2>400 dpi:</h2>Higher image quality.<br/><br/>Produces very large file size.<br/><br/>Intended primarly for high quality printing. Used for originals that have thin lines, small font sizes, or are going to be enlarged.",
        "RES_600X600_DESC": "<h2>600 dpi:</h2>Highest image quality.<br/><br/>Produces extreamly large file size.<br/><br/>Intended for commercial printing.",
		"right": "Right",
    	"saturation": "Saturation",
    	"scan": "Scan",
    	"scanPresets": "Scan Presets",
    	"scanToUSB": "ScanToUSB",
    	"SEARCHABLE_IMAGE": "Searchable",
        "sharingAndPrinting": "Sharing and Printing",
        "sharingAndPrintingDesc": "This setting is best for sharing files to be viewed on-screen and for printing most standard business documents.<br/><br/>Using this setting will result in small file sizes and normal image quality.",
    	//"sharingAndPrintingDescLine1": "This setting is best for sharing files to be viewed on-screen and for printing most standard business documents.",
    	//"sharingAndPrintingDescLine2": "Using this setting will result in small file sizes and normal image quality.",
    	"sharpen": "Sharpen",
    	"sharpness": "Sharpness",
    	"HEAD_TO_FEED_EDGE": "Sideways",
        "simpleScan": "Simple Scan",
        "simpleScanDesc": "This setting is best for faster processing bu may result in excessivly large file sizes.<br/><br/>Using this setting will apply only minimal image processing and compression.",
    	"smallFileSize": "Small File Size",
		"soften": "Soften",
    	"template1": "Template 1",
        "templateDataError": "Error: this template is missing some information",
    	"TEXT": "Text",
		"top": "Top",
    	"TWO_SIDED": "2-Sided",
    	"SECOND_SIDE_ROTATION": "2-Sided, Rotate Side 2",
    	"twoSidedScaning": "2-Sided Scaning",
        "validPairs": "Valid pairs:",
    	"vivid": "Vivid",
    	"width": "Width",
    	"workflowScanning": "Workflow Scanning",
    	"updateNow": "Update Now",
    	"updateTemplates": "Update Templates",
    	"updateTemplatesDescr1": "Use this feature only if existing templates have been changed or new templates have been created since the last update.",
    	"updateTemplatesDescr2": "Note: Automatic template updates can be scheduled using configuration Web pages associated with this device.",
    	"updateTemplatesDescr3": "Contact the system administrator for assistance.",
    	"HEAD_TO_TOP": "Upright",
    	"usb": "USB",

        //Audit copy
        "destinationname": "Destination name",
        "enter_destination_name": "Enter destination",
        "ipaddress": "Host or ip with port",
        "enter_host": "Enter host and port",
        "sharedresource": "Share",
        "enter_share": "Enter share name",
        "pathtodocument": "Path",
        "enter_path": "Enter path",
        "loginname": "Username",
        "enter_username": "Enter username",
        "password": "Password",
        "enter_password": " Enter password",
        "licenseKey": "License Key",
        "enterLicenseKey": "Enter License Key"
    });

    $translateProvider.preferredLanguage('en');
  });



$(function () {



    FastClick.attach(document.body);

});

app.filter('removeQuotes', function(){
    return function (item) {
        return item.replace(/['"]+/g, '');
    };
  });  
